// Auth Constants
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const LOGOUT_REQUEST  = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS  = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE  = 'LOGOUT_FAILURE';

// Issue Constants
export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';
export const FETCH_USER_ISSUES_REQUEST = 'FETCH_USER_ISSUES_REQUEST';
export const FETCH_USER_ISSUES_SUCCESS = 'FETCH_USER_ISSUES_SUCCESS';
export const FETCH_USER_ISSUES_FAILURE = 'FETCH_USER_ISSUES_FAILURE';
export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const CREATE_ISSUE_FAILURE = 'CREATE_ISSUE_FAILURE';
export const DELETE_ISSUE_REQUEST = 'DELETE_ISSUE_REQUEST';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
export const DELETE_ISSUE_FAILURE = 'DELETE_ISSUE_FAILURE';
export const FETCH_ISSUE_BY_ID_REQUEST = 'FETCH_ISSUE_BY_ID_REQUEST';
export const FETCH_ISSUE_BY_ID_SUCCESS = 'FETCH_ISSUE_BY_ID_SUCCESS';
export const FETCH_ISSUE_BY_ID_FAILURE = 'FETCH_ISSUE_BY_ID_FAILURE';
export const CLEAR_CURRENT_ISSUE = 'CLEAR_CURRENT_ISSUE';

// Vote Constants
export const CAST_VOTE_REQUEST = 'CAST_VOTE_REQUEST';
export const CAST_VOTE_SUCCESS = 'CAST_VOTE_SUCCESS';
export const CAST_VOTE_FAILURE = 'CAST_VOTE_FAILURE';

// Analytics Constants
export const FETCH_CATEGORY_ANALYTICS_REQUEST = 'FETCH_CATEGORY_ANALYTICS_REQUEST';
export const FETCH_CATEGORY_ANALYTICS_SUCCESS = 'FETCH_CATEGORY_ANALYTICS_SUCCESS';
export const FETCH_CATEGORY_ANALYTICS_FAILURE = 'FETCH_CATEGORY_ANALYTICS_FAILURE';
export const FETCH_SUBMISSION_ANALYTICS_REQUEST = 'FETCH_SUBMISSION_ANALYTICS_REQUEST';
export const FETCH_SUBMISSION_ANALYTICS_SUCCESS = 'FETCH_SUBMISSION_ANALYTICS_SUCCESS';
export const FETCH_SUBMISSION_ANALYTICS_FAILURE = 'FETCH_SUBMISSION_ANALYTICS_FAILURE';
export const FETCH_MOST_VOTED_ANALYTICS_REQUEST = 'FETCH_MOST_VOTED_ANALYTICS_REQUEST';
export const FETCH_MOST_VOTED_ANALYTICS_SUCCESS = 'FETCH_MOST_VOTED_ANALYTICS_SUCCESS';
export const FETCH_MOST_VOTED_ANALYTICS_FAILURE = 'FETCH_MOST_VOTED_ANALYTICS_FAILURE';

// Map Constants
export const FETCH_MAP_ISSUES_REQUEST = 'FETCH_MAP_ISSUES_REQUEST';
export const FETCH_MAP_ISSUES_SUCCESS = 'FETCH_MAP_ISSUES_SUCCESS';
export const FETCH_MAP_ISSUES_FAILURE = 'FETCH_MAP_ISSUES_FAILURE';